openapi: 3.1.0
x-stoplight:
  id: tgvfiv56rre5x
info:
  title: POS PAX Public API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /configuration:
    get:
      summary: POS configuration
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: get-configuration
      description: 'First endpoint to be called after login, returns POS configuration.'
      x-internal: false
    parameters: []
  '/cards/{track}':
    get:
      summary: Card info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card-info'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '':
          description: ''
      operationId: get-cards
    parameters:
      - schema:
          type: string
        name: track
        in: path
        required: true
  /devices/pax/supplies/info:
    get:
      summary: Supplies info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplies-info'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-devices-pax-supplies-info
      parameters:
        - schema:
            type: string
          in: query
          name: card_id
        - schema:
            type: string
          in: query
          name: type_card_id
        - schema:
            type: string
          in: query
          name: is_oil
  /supplies/validation:
    post:
      summary: Validate and save supply
      operationId: post-supplies-validation
      responses:
        '200':
          description: OK
  /devices/pax/reversal/info:
    get:
      summary: Get last reversal info
      tags: []
      responses: {}
      operationId: get-devices-pax-reversal-info
      parameters:
        - schema:
            type: string
          in: query
          name: card_id
        - schema:
            type: string
          in: query
          name: card_type_id
        - schema:
            type: string
          in: query
          name: is_oil
  '/rewards/{track}':
    parameters:
      - schema:
          type: string
        name: track
        in: path
        required: true
        description: Track 2 of the requested card
    get:
      summary: Available rewards
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: List of campaign which has available rewards for the input card
                items:
                  $ref: '#/components/schemas/CampaignRewards'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-rewards-track
      description: 'For point cards, return the list of available rewards, filtering with available points and active campaigns.'
  /transactions/preauth:
    post:
      summary: Preauth request
      operationId: post-transactions-preauth
      responses:
        '200':
          description: OK. You need to check inside the body to retrieve the preauth request result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreauthResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      description: Used to check if the card has enough credit to perform the operation.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreauthRequest'
              description: Preauth request data
components:
  schemas:
    Configuration:
      type: object
      properties:
        terminal_id:
          type: integer
        supplier_id:
          type: integer
        card_types:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              code:
                type: integer
        measure_units:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              measure_unit:
                type: string
        enabled_card_types:
          type: array
          items:
            type: integer
        articles:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              unit_price:
                type: number
              is_oil:
                type: boolean
              price_level_id:
                type: integer
              measure_unit_id:
                type: integer
      x-examples:
        Example 1:
          terminal_id: 0
          supplier_id: 225
          card_types:
            - id: 2
              name: RICARICABILE
              code: 3
            - id: 3
              name: SCONTO
              code: 1
            - id: 4
              name: RACCOLTA PUNTI
              code: 4
            - id: 5
              name: FINEMESE
              code: 2
            - id: 6
              name: BUONO CARB.
              code: 6
          measure_units:
            - id: 1
              name: Lt
              measure_unit: L
            - id: 2
              name: Kg
              measure_unit: W
            - id: 3
              name: N.
              measure_unit: U
            - id: 4
              name: Ore
              measure_unit: H
          enabled_card_types:
            - 2
            - 3
            - 4
            - 5
            - 6
          articles:
            - id: 1172
              name: GASOLIO
              unit_price: 2.08
              is_oil: true
              price_level_id: 2
            - id: 1172
              name: GASOLIO
              unit_price: 1.998
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 1.859
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 2.05
              is_oil: true
              price_level_id: 2
            - id: 1176
              name: GPL
              unit_price: 0.799
              is_oil: true
              price_level_id: 2
            - id: 256
              name: Ricarica carta fuel
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 257
              name: Buoni carburante
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 2984
              name: ADBLUE TANICA
              is_oil: false
              measure_unit_id: 3
            - id: 3003
              name: OLIO
              is_oil: false
              measure_unit_id: 1
            - id: 3065
              name: LAVAGGIO BUS
              is_oil: false
              measure_unit_id: 3
            - id: 3451
              name: ACCESSORI
              is_oil: false
              measure_unit_id: 3
            - id: 3518
              name: PARCHEGGIO
              is_oil: false
              measure_unit_id: 3
            - id: 3620
              name: LAVAGGIO AUTO
              is_oil: false
              measure_unit_id: 3
            - id: 4995
              name: Marca da bollo
              unit_price: 2
              is_oil: false
              measure_unit_id: 3
            - id: 5904
              name: Spese carta Finemese
              is_oil: false
              measure_unit_id: 3
      examples:
        - terminal_id: 0
          supplier_id: 225
          card_types:
            - id: 2
              name: RICARICABILE
              code: 3
            - id: 3
              name: SCONTO
              code: 1
            - id: 4
              name: RACCOLTA PUNTI
              code: 4
            - id: 5
              name: FINEMESE
              code: 2
            - id: 6
              name: BUONO CARB.
              code: 6
          measure_units:
            - id: 1
              name: Lt
              measure_unit: L
            - id: 2
              name: Kg
              measure_unit: W
            - id: 3
              name: N.
              measure_unit: U
            - id: 4
              name: Ore
              measure_unit: H
          enabled_card_types:
            - 2
            - 3
            - 4
            - 5
            - 6
          articles:
            - id: 1172
              name: GASOLIO
              unit_price: 2.08
              is_oil: true
              price_level_id: 2
            - id: 1172
              name: GASOLIO
              unit_price: 1.998
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 1.859
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 2.05
              is_oil: true
              price_level_id: 2
            - id: 1176
              name: GPL
              unit_price: 0.799
              is_oil: true
              price_level_id: 2
            - id: 256
              name: Ricarica carta fuel
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 257
              name: Buoni carburante
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 2984
              name: ADBLUE TANICA
              is_oil: false
              measure_unit_id: 3
            - id: 3003
              name: OLIO
              is_oil: false
              measure_unit_id: 1
            - id: 3065
              name: LAVAGGIO BUS
              is_oil: false
              measure_unit_id: 3
            - id: 3451
              name: ACCESSORI
              is_oil: false
              measure_unit_id: 3
            - id: 3518
              name: PARCHEGGIO
              is_oil: false
              measure_unit_id: 3
            - id: 3620
              name: LAVAGGIO AUTO
              is_oil: false
              measure_unit_id: 3
            - id: 4995
              name: Marca da bollo
              unit_price: 2
              is_oil: false
              measure_unit_id: 3
            - id: 5904
              name: Spese carta Finemese
              is_oil: false
              measure_unit_id: 3
    Card-info:
      type: object
      x-examples:
        Example 1:
          id: 0
          is_enabled: true
          type_id: 0
      properties:
        is_enabled:
          type: boolean
        type_id:
          type: integer
      description: Card type and status informations
    Supplies-info:
      type: object
      properties:
        customer_data:
          type: array
          items:
            type: integer
        articles:
          type: array
          items:
            type: integer
        requires_pin:
          type: boolean
      x-examples:
        Example 1:
          customer_data:
            - 2
            - 3
          articles:
            - 3
            - 4
            - 8
          requires_pin: true
    Reward:
      type: object
      x-examples:
        Example 1:
          id: 10
          name: Buono Euro 10
          points: 300
          is_fuelcoupon: false
      examples:
        - id: 0
          name: string
          points: 0
          is_fuelcoupon: true
      properties:
        id:
          type: integer
          description: Id of the reward
        name:
          type: string
          description: Name/description of the reward
        points:
          type: integer
          description: Point cost of the reward
        is_fuelcoupon:
          type: boolean
          description: 'True if the reward is a fuel coupon, false otherwise'
      required:
        - id
        - name
        - points
        - is_fuelcoupon
      description: Model a single reward data
    CampaignRewards:
      title: CampaignRewards
      x-stoplight:
        id: qjbhk1o80xtrn
      type: object
      description: A campaign with all its rewards
      properties:
        id:
          type: integer
          description: ID of the campaign
        name:
          type: string
          description: Name of the campaign
        type:
          type: integer
          description: |-
            Allowed values are:

            - 1: this is a OIL campaign
            - 2: this is a NON OIL campaign
            - 3: this is a mixed campaign
        rewards:
          type: array
          description: Arrray of available rewards
          items:
            $ref: '#/components/schemas/Reward'
      required:
        - id
        - name
        - type
        - rewards
    PreauthRequest:
      title: PreauthRequest
      x-stoplight:
        id: t7g43q1jbdgvy
      type: object
      description: Used to create a preauthorization request
      properties:
        card_track:
          type: string
          description: 'Track of the used card. Example: 70055730001000057=2209009000615800000'
        random_pin_key:
          type: string
          description: Random pin key used to generate the session encryption key
        label_key:
          type: string
          description: Label used to recognize which key use on server side
        crypted_pin:
          type: string
          description: The pin encrypted with the session key
        datetime:
          type: string
          description: Datetime of the request
          format: date-time
        total_amount:
          type: number
          description: Amount requested to be authorized
        tran_id:
          type: integer
          description: Transaction id
      required:
        - card_track
        - random_pin_key
        - label_key
        - crypted_pin
        - datetime
        - total_amount
        - tran_id
    PreauthResponse:
      title: PreauthResponse
      x-stoplight:
        id: 6nlcd7ng8mgkw
      type: object
      properties:
        action_code:
          type: string
          description: The action code is the status of the request. Action codes starting with '0' are considered as a positive response.
        approval_code:
          type: string
          description: Approval code generated for positive responses.
        authorized_amount:
          type: number
          description: The authorized amount with this request
        available_products:
          type: array
          description: Products available for this card
          items:
            type: string
        vehicle_plate:
          type: string
          description: Option vehicle plate binded to the card
        icc_data:
          type: string
          description: 'ICC data, for EMV transactions'
        balance_amount:
          type: number
          description: Total balance amount
      required:
        - action_code
        - approval_code
        - authorized_amount
        - available_products
        - vehicle_plate
        - icc_data
        - balance_amount
    SupplyOilInput:
      title: SupplyOilInput
      x-stoplight:
        id: 6pd5lgrxsz2xt
      type: object
      description: Input model for the supplies requests
      properties:
        card_track:
          type: string
          description: 'Track of the used card. Example: 70055730001000057=2209009000615800000'
        tran_id:
          type: integer
          description: Transaction id
        products:
          type:
            - array
          description: List of products bought
          items:
            type: object
            properties:
              product_code:
                type: string
                description: Product's code
              unit_of_measure:
                type: string
                description: Product's unit of measure
              quantity:
                type: number
                description: Product's quantity
              unit_price:
                type: number
                description: Product's unit price
              amount:
                type: number
                description: Product's amount
            required:
              - product_code
              - unit_of_measure
              - quantity
              - unit_price
              - amount
        random_pin_key:
          type: string
        label_key:
          type: string
        crypted_pin:
          type: string
        date_time:
          type: string
        total_amount:
          type: number
        km:
          type: integer
        drivercode:
          type: integer
        vehiclecode:
          type: string
        pos_data_code:
          type: string
        function_code:
          type: string
        message_reason_code:
          type: string
        batch_number:
          type: string
        currency_code:
          type: string
        icc_related_data:
          type: string
        unencrypted_id:
          type: string
        work_order:
          type: string
        vehicle_number:
          type: string
        driver_id:
          type: string
        service_level:
          type: boolean
        delivery_note_number:
          type: string
        default_vat:
          type: string
      required:
        - card_track
        - tran_id
        - products
        - random_pin_key
    SupplyOilOutput:
      type: object
      properties:
        action_code:
          type: string
        approval_code:
          type: string
        vehicle_plate:
          type: string
        icc_data:
          type: string
      x-examples:
        Example 1:
          action_code: '000'
          approval_code: '123'
          vehicle_plate: 12ABC34
          icc_data: DF2003ABCDEF
      description: Output model for the supplies requests
  securitySchemes:
    Cognito:
      type: oauth2
      flows:
        password:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
security:
  - Cognito: []
