openapi: 3.1.0
x-stoplight:
  id: tgvfiv56rre5x
info:
  title: POS PAX Public API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /configuration:
    get:
      summary: POS configuration
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: get-configuration
      description: 'First endpoint to be called after login, returns POS configuration.'
      x-internal: false
    parameters: []
  '/cards/{track}':
    get:
      summary: Card info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card-info'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '':
          description: ''
      operationId: get-cards
    parameters:
      - schema:
          type: string
        name: track
        in: path
        required: true
  /supplies/validation:
    post:
      summary: ''
      operationId: post-supplies-validation
      responses:
        '200':
          description: OK
  /transactions/info/reversal:
    get:
      summary: Transaction reversal info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoPosTransactionReversal'
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '500':
          description: Internal Server Error
      operationId: get-devices-pax-reversal-info
      parameters:
        - schema:
            type: string
          in: query
          name: card_track
        - schema:
            type: string
          in: query
          name: is_oil
    parameters: []
  '/rewards/{track}':
    parameters:
      - schema:
          type: string
        name: track
        in: path
        required: true
        description: Track 2 of the requested card
  /transactions/info:
    get:
      summary: Retrieve info to perform an oil or nonoil transaction
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionInfo'
      operationId: get-transaction-info
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: is_oil
        - schema:
            type: string
          in: query
          name: card_track
    parameters: []
  /recharges/reversal:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RechargesReversal'
              examples:
                Example 1:
                  value:
                    id: 529818
                    date_time: '2023-01-20T17:45:24Z'
                    bill: 100
                    bonus_credit: 20
                    update_required: false
                    requires_pin: true
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity (WebDAV)
        '500':
          description: Internal Server Error
      operationId: get-recharges-reversal
      parameters:
        - schema:
            type: string
          in: query
          name: card_track
  /recharges:
    post:
      summary: Memorize recharge
      operationId: post-recharges
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
components:
  schemas:
    Configuration:
      type: object
      properties:
        terminal_id:
          type: integer
        supplier_id:
          type: integer
        card_types:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              code:
                type: integer
        measure_units:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              measure_unit:
                type: string
        enabled_card_types:
          type: array
          items:
            type: integer
        articles:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              unit_price:
                type: number
              is_oil:
                type: boolean
              price_level_id:
                type: integer
              measure_unit_id:
                type: integer
      x-examples:
        Example 1:
          terminal_id: 0
          supplier_id: 225
          card_types:
            - id: 2
              name: RICARICABILE
              code: 3
            - id: 3
              name: SCONTO
              code: 1
            - id: 4
              name: RACCOLTA PUNTI
              code: 4
            - id: 5
              name: FINEMESE
              code: 2
            - id: 6
              name: BUONO CARB.
              code: 6
          measure_units:
            - id: 1
              name: Lt
              measure_unit: L
            - id: 2
              name: Kg
              measure_unit: W
            - id: 3
              name: N.
              measure_unit: U
            - id: 4
              name: Ore
              measure_unit: H
          enabled_card_types:
            - 2
            - 3
            - 4
            - 5
            - 6
          articles:
            - id: 1172
              name: GASOLIO
              unit_price: 2.08
              is_oil: true
              price_level_id: 2
            - id: 1172
              name: GASOLIO
              unit_price: 1.998
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 1.859
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 2.05
              is_oil: true
              price_level_id: 2
            - id: 1176
              name: GPL
              unit_price: 0.799
              is_oil: true
              price_level_id: 2
            - id: 256
              name: Ricarica carta fuel
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 257
              name: Buoni carburante
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 2984
              name: ADBLUE TANICA
              is_oil: false
              measure_unit_id: 3
            - id: 3003
              name: OLIO
              is_oil: false
              measure_unit_id: 1
            - id: 3065
              name: LAVAGGIO BUS
              is_oil: false
              measure_unit_id: 3
            - id: 3451
              name: ACCESSORI
              is_oil: false
              measure_unit_id: 3
            - id: 3518
              name: PARCHEGGIO
              is_oil: false
              measure_unit_id: 3
            - id: 3620
              name: LAVAGGIO AUTO
              is_oil: false
              measure_unit_id: 3
            - id: 4995
              name: Marca da bollo
              unit_price: 2
              is_oil: false
              measure_unit_id: 3
            - id: 5904
              name: Spese carta Finemese
              is_oil: false
              measure_unit_id: 3
      examples:
        - terminal_id: 0
          supplier_id: 225
          card_types:
            - id: 2
              name: RICARICABILE
              code: 3
            - id: 3
              name: SCONTO
              code: 1
            - id: 4
              name: RACCOLTA PUNTI
              code: 4
            - id: 5
              name: FINEMESE
              code: 2
            - id: 6
              name: BUONO CARB.
              code: 6
          measure_units:
            - id: 1
              name: Lt
              measure_unit: L
            - id: 2
              name: Kg
              measure_unit: W
            - id: 3
              name: N.
              measure_unit: U
            - id: 4
              name: Ore
              measure_unit: H
          enabled_card_types:
            - 2
            - 3
            - 4
            - 5
            - 6
          articles:
            - id: 1172
              name: GASOLIO
              unit_price: 2.08
              is_oil: true
              price_level_id: 2
            - id: 1172
              name: GASOLIO
              unit_price: 1.998
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 1.859
              is_oil: true
              price_level_id: 1
            - id: 1174
              name: VERDE
              unit_price: 2.05
              is_oil: true
              price_level_id: 2
            - id: 1176
              name: GPL
              unit_price: 0.799
              is_oil: true
              price_level_id: 2
            - id: 256
              name: Ricarica carta fuel
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 257
              name: Buoni carburante
              unit_price: 1
              is_oil: false
              measure_unit_id: 3
            - id: 2984
              name: ADBLUE TANICA
              is_oil: false
              measure_unit_id: 3
            - id: 3003
              name: OLIO
              is_oil: false
              measure_unit_id: 1
            - id: 3065
              name: LAVAGGIO BUS
              is_oil: false
              measure_unit_id: 3
            - id: 3451
              name: ACCESSORI
              is_oil: false
              measure_unit_id: 3
            - id: 3518
              name: PARCHEGGIO
              is_oil: false
              measure_unit_id: 3
            - id: 3620
              name: LAVAGGIO AUTO
              is_oil: false
              measure_unit_id: 3
            - id: 4995
              name: Marca da bollo
              unit_price: 2
              is_oil: false
              measure_unit_id: 3
            - id: 5904
              name: Spese carta Finemese
              is_oil: false
              measure_unit_id: 3
    Card-info:
      type: object
      x-examples:
        Example 1:
          id: 0
          is_enabled: true
          type_id: 0
      properties:
        is_enabled:
          type: boolean
        type_id:
          type: integer
      description: Card type and status informations
    Supplies-info:
      type: object
      properties:
        customer_data:
          type: array
          items:
            type: integer
        articles:
          type: array
          items:
            type: integer
        requires_pin:
          type: boolean
      x-examples:
        Example 1:
          customer_data:
            - 2
            - 3
          articles:
            - 3
            - 4
            - 8
          requires_pin: true
    SupplyNonOilInput:
      type: object
      x-examples:
        Example 1:
          card_track: 70055730001000065=2209009000615800000
          total_amount: 2
          date_time: '2023-05-11T09:00:00.000'
          tran_id: 1234567890
          transaction_details:
            - article_code: '1'
              quantity: 2
              unit_price: 1
              amount: 2
          card_pin: 56ABD55E11D4FF0D2F7136943BF2E49C
      properties:
        card_track:
          type: string
          description: 'Track of the used card. Example: 70055730001000057=2209009000615800000'
        total_amount:
          type: number
          description: Transaction's total amount that the host should authorize
        date_time:
          type: string
          description: 'Request date time '
        tran_id:
          type: integer
          description: Transaction id
        transaction_details:
          description: List of bought articles with details
          type: array
          items:
            type: object
            properties:
              article_code:
                type: string
                description: Article code bought
              quantity:
                type: integer
                description: 'Article quantity '
              unit_price:
                type: number
                description: Article unit price
              amount:
                type: number
                description: 'Article amount '
            required:
              - article_code
              - quantity
              - unit_price
              - amount
        card_pin:
          type: string
          description: Card pin encrypted
      required:
        - card_track
        - total_amount
        - date_time
        - tran_id
        - transaction_details
        - card_pin
    SupplyNonOilOutput:
      type: object
      x-examples:
        Example 1:
          action_code: '000'
          approval_code: '123'
          vehicle_plate: 12ABC34
      properties:
        action_code:
          type: string
          description: The action code is the status of the request. Action codes starting with '0' are considered as a positive response.
        approval_code:
          type: string
          description: Approval code generated for positive responses.
        vehicle_plate:
          type: string
          description: Option vehicle plate binded to the card
      required:
        - action_code
    Articles:
      title: Articles
      x-stoplight:
        id: 8db3394aaad8f
      type: array
      description: Articles model for info pos transaction reversal model
      items:
        type: object
        properties:
          article_name:
            type: string
            description: name of the article
          amount:
            type: number
            description: amount of the transaction
          unit_price:
            type: number
            description: unit price of the transaction
          quantity:
            type: number
            description: quantity of the transaction
    InfoPosTransactionReversal:
      title: InfoPosTransactionReversal
      x-stoplight:
        id: 3holszdjt79rb
      type: object
      examples: []
      properties:
        id:
          type: integer
          description: transaction id unique
        date_time:
          type: string
          format: date-time
          description: data time of the transaction
          readOnly: true
        articles:
          $ref: '#/components/schemas/Articles'
          description: articles model of the transaction
        update_required:
          type: boolean
          description: true if the terminal must update its settings
        requires_pin:
          type: boolean
          description: 'true if the pin mandatory for the next reversal '
        is_oil:
          type: boolean
          customer_data:
            - 2
            - 3
          is_oil: false
          articles:
            - 3
            - 4
            - 8
          requires_pin: true
    RechargesReversal:
      title: RechargesReversal
      x-stoplight:
        id: zcwnf9vyzktqx
      type: object
      properties:
        id:
          type: integer
          description: id unique
        date_time:
          type: string
          format: date-time
          readOnly: true
        bill:
          type: number
        bonus_credit:
          type: number
        update_required:
          type: boolean
          description: true if the terminal must update its settings
        requires_pin:
          type: boolean
          description: 'true if the pin mandatory for the next reversal '
    RechargesInput:
      type: object
      properties:
        card_track:
          type: string
        bill_id:
          type: integer
        pin:
          type: string
        payment_mode:
          type: integer
        key_label:
          type: string
        random_pin_key:
          type: string
        transaction_id:
          type: string
      x-examples:
        Example 1:
          card_track: 70055730001000057=2209009000615800000
          bill_id: 53
          pin: 68B4E28A576654D1
          payment_mode: 2
          key_label: QT_IFSF
          random_pin_key: 2C9E11B025F712CA37437D853BD6E7D4
          transaction_id: ''
  securitySchemes:
    Cognito:
      type: oauth2
      flows:
        password:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
  responses: {}
security:
  - Cognito: []
